language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t culmi/docker-react -f ./docker/workflow/frontend/Dockerfile.dev ./docker/workflow/frontend

script:
    - docker run -e CI=true culmi/docker-react npm run test