language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t culmi/react-test -f ./docker/complex/client/Dockerfile.dev ./docker/complex/client

script:
    - docker run culmi/react-test npm run test -- --coverage

after_success:
    - docker build -t culmi/multi-client ./docker/complex/client
    - docker build -t culmi/multi-server ./docker/complex/server
    - docker build -t culmi/multi-worker ./docker/complex/worker    
    - docker build -t culmi/multi-nginx ./docker/complex/nginx

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push culmi/multi-client 
    - docker push culmi/multi-server 
    - docker push culmi/multi-worker 
    - docker push culmi/multi-nginx 
    
